name: Docker push

on:
  push:
    branches:
      - main

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"    
      
      - name: Docker push
        run: make image_tag=${{ steps.vars.outputs.sha_short }} docker_push